In [5]:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

import pandas as pd
import numpy as np
dataset = pd.read_excel('./Dataset/CCPP/CCPP_dataset.xlsx')

print(dataset.head())

      AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90


In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
print(scaler.fit_transform(dataset))
dataset = scaler.fit_transform(dataset)

[[-0.62951938 -0.98729659  1.8204884  -0.00951935  0.52120807]
 [ 0.74190911  0.68104512  1.1418628  -0.97462052 -0.58566442]
 [-1.95129733 -1.17301765 -0.18507756  1.2898397   2.00367889]
 ...
 [ 1.56583973  1.57581141 -0.05709854 -2.52261812 -1.45288056]
 [ 0.64797565  1.19177803  0.1011913  -0.74790051 -1.09134518]
 [ 0.26150656  0.64641916  0.66867722 -0.37254534 -0.06357687]]


In [7]:
from sklearn.model_selection import train_test_split

X, y = dataset[:, : 4] , dataset[: , 4]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
#print(X_train, y_test)

In [15]:
from sklearn.svm import SVR
from sklearn import linear_model
from sklearn import svm


svm_reg =    SVR()
sgd_reg =    linear_model.SGDRegressor()
bay_reg =    linear_model.BayesianRidge()
las_reg =    linear_model.LassoLars()
ard_reg =    linear_model.ARDRegression()
pag_reg =    linear_model.PassiveAggressiveRegressor()
lin_reg =    linear_model.LinearRegression()


In [17]:
from sklearn.metrics import mean_squared_error

for reg in (svm_reg, sgd_reg, bay_reg, las_reg, ard_reg, pag_reg, lin_reg):
    reg.fit(X_train, y_train)
    prediction = reg.predict(X_test)
    print(reg.__class__.__name__, "      ", mean_squared_error(y_test, prediction))


SVR        0.05294232716855608
SGDRegressor        0.06975829455132104
BayesianRidge        0.06960745120298706
LassoLars        0.9962749092436307
ARDRegression        0.06960922620737599
PassiveAggressiveRegressor        0.25173751229003966
LinearRegression        0.06960884287546201
